// glashjs offline layer
// ---------------------------------------------------------------------------
// Generates a Service Worker that makes a built glashjs site usable offline
// after the first visit — exactly the behavior requested: the whole live
// project is cached into small hashed files; once cached, the site works with
// no internet, EXCEPT freshly-updated data and live/streaming features, which
// are gated behind a network-first strategy so they degrade gracefully.
//
// Strategies:
//   - App shell + hashed assets : cache-first (immutable, hash-busted on deploy)
//   - HTML navigations          : stale-while-revalidate (instant, self-heals)
//   - /api, /rest, /auth, live  : network-first, fall back to a cached "offline"
//                                 marker so the app can show a degraded state
import { promises as fs } from 'node:fs';
import path from 'node:path';

const DATA_PREFIXES = ['/api/', '/rest/', '/auth/', '/realtime', '/live', '/stream'];

function swSource({ cacheName, precache, dataPrefixes }) {
  return `// AUTO-GENERATED by glashjs. Do not edit by hand.
const CACHE = ${JSON.stringify(cacheName)};
const PRECACHE = ${JSON.stringify(precache, null, 0)};
const DATA_PREFIXES = ${JSON.stringify(dataPrefixes)};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Precache in chunks so one failure doesn't abort the whole install.
    await Promise.allSettled(PRECACHE.map((url) => cache.add(url)));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

function isData(url) {
  return DATA_PREFIXES.some((p) => url.pathname.startsWith(p));
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Live/updated data: network-first, fall back to cache, then a degraded marker.
  if (isData(url)) {
    event.respondWith((async () => {
      try {
        const fresh = await fetch(request);
        return fresh;
      } catch {
        const cached = await caches.match(request);
        if (cached) return cached;
        return new Response(JSON.stringify({ offline: true, error: 'offline: live data unavailable' }), {
          status: 503, headers: { 'content-type': 'application/json', 'x-glash-offline': '1' },
        });
      }
    })());
    return;
  }

  // HTML navigations: stale-while-revalidate.
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const cached = await cache.match(request);
      const network = fetch(request).then((res) => { cache.put(request, res.clone()); return res; }).catch(() => null);
      return cached || (await network) || cache.match('/offline.html') || new Response('offline', { status: 503 });
    })());
    return;
  }

  // Hashed static assets: cache-first.
  event.respondWith((async () => {
    const cached = await caches.match(request);
    if (cached) return cached;
    try {
      const res = await fetch(request);
      const cache = await caches.open(CACHE);
      cache.put(request, res.clone());
      return res;
    } catch {
      return cached || new Response('offline', { status: 503 });
    }
  })());
});
`;
}

/**
 * Write a Service Worker + a small registration snippet into `outDir`.
 * `manifest` is the object returned by optimizeAssets(); we precache the best
 * (smallest) variant of each asset plus any provided `appShell` URLs.
 */
export async function generateServiceWorker(outDir, manifest, {
  cacheName,
  appShell = ['/', '/index.html', '/offline.html', '/favicon.svg'],
  dataPrefixes = DATA_PREFIXES,
} = {}) {
  const version = manifest?.version || 'dev';
  const cache = cacheName || `glash-${version}`;

  const assetUrls = new Set(appShell);
  for (const [rel, entry] of Object.entries(manifest?.assets ?? {})) {
    // Prefer the smallest modern variant; fall back to the original path.
    const v = entry.variants || {};
    const best = v.avif?.path || v.webp?.path || v.br?.path || rel;
    assetUrls.add('/' + best.replace(/^\//, ''));
  }

  const sw = swSource({ cacheName: cache, precache: [...assetUrls], dataPrefixes });
  const reg = `// glashjs SW registration — import this once from your entry.
export function registerGlashOffline() {
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return;
  window.addEventListener('load', () => navigator.serviceWorker.register('/glash-sw.js').catch(() => {}));
}
`;

  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(path.join(outDir, 'glash-sw.js'), sw);
  await fs.writeFile(path.join(outDir, 'glash-offline.mjs'), reg);
  return { serviceWorker: 'glash-sw.js', precached: assetUrls.size };
}
